import type { NextPage, GetStaticProps } from "next";
import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Home: NextPage = (props) => {
  useEffect(() => {
    if (window) {
      const data = window.localStorage.getItem("links");
      console.log(data);
    }
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Link Shorter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <nav className={styles.navbar}>
          <div className={styles.left}>
            <h1 className={styles.logo}>Shortly</h1>
            <div className={styles.links}>
              <a className={styles.link}>Features</a>
              <a className={styles.link}>Pricing</a>
              <a className={styles.link}>Resources</a>
            </div>
          </div>
          <div className={styles.right}>
            <button className={styles.login}>Login</button>
            <button className={styles.signup}>Sign Up</button>
          </div>
        </nav>
        <section className={styles.hero}>
          <div className={styles.main}>
            <div className={styles.leftside}>
              <h1>More than just shorter links</h1>
              <p>
                Build your brand’s recognition and get detailed insights on how
                your links are performing.
              </p>
              <button>Get Started</button>
            </div>
            <div className={styles.rightside}>Image</div>
          </div>

          <div className={styles.linkinput}>
            <input type="text" placeholder="Shorten a link here..." />

            <button>Shorten It!</button>
          </div>
        </section>
        <section className={styles.cardsection}>
          <div className={styles.cardsectitle}>
            Advanced Statistics Track how your links are performing across the
            web with our advanced statistics dashboard.
          </div>
          <div className={styles.cards}>
            <div className={styles.card}>
              Brand Recognition Boost your brand recognition with each click.
              Generic links don’t mean a thing. Branded links help instil
              confidence in your content.
            </div>
            <div className={styles.card}>
              Detailed Records Gain insights into who is clicking your links.
              Knowing when and where people engage with your content helps
              inform better decisions.
            </div>
            <div className={styles.card}>
              Fully Customizable Improve brand awareness and content
              discoverability through customizable links, supercharging audience
              engagement.
            </div>
          </div>
        </section>

        <section className={styles.calltoaction}>
          <h2 className={styles.title}>Boost your links today</h2>
          <button className={styles.started}>Get Started</button>
        </section>
        <footer className={styles.footer}>
          <h3 className={styles.logo}>Shortly</h3>
          <div className={styles.links}>
            <h4>Features</h4> <a href="#">Link Shortening</a>{" "}
            <a href="#">Branded Links</a> <a href="#">Analytics</a>{" "}
          </div>
          <div className={styles.links}>
            <h4>Resources</h4> <a href="#">Blog</a> <a href="#"> Developers</a>{" "}
            <a href="#"> Support</a>{" "}
          </div>
          <div className={styles.links}>
            <h4>Company</h4> <a href="#">About</a> <a href="#">Our Team</a>{" "}
            <a href="#">Careers</a> <a href="#">Contact</a>{" "}
          </div>
        </footer>
      </div>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      exapmle: "example",
    },
  };
};
