import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Link Shorter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <nav className={styles.navbar}>
          <div className={styles.logo}>Shortly</div>
          <div>
            <a className={styles.link}>Features</a>
            <a className={styles.link}>Pricing</a>
            <a className={styles.link}>Resources</a>
          </div>
          <div>
            <button className={styles.login}>Login</button>
            <button className={styles.signup}>Sign Up</button>
          </div>
        </nav>
        <section className={styles.hero}>
          <div>
            <div>
              <h1>More than just shorter links</h1>
              <p>
                Build your brand’s recognition and get detailed insights on how
                your links are performing.
              </p>
              <button>Get Started</button>
            </div>
            <div>Image</div>
          </div>

          <div>
            <input type="text" placeholder="Shorten a link here..." />

            <button>Shorten It!</button>
          </div>
        </section>
        <section>
          <div>
            Advanced Statistics Track how your links are performing across the
            web with our advanced statistics dashboard.
          </div>
          <div>
            <div>
              Brand Recognition Boost your brand recognition with each click.
              Generic links don’t mean a thing. Branded links help instil
              confidence in your content.
            </div>
            <div>
              Detailed Records Gain insights into who is clicking your links.
              Knowing when and where people engage with your content helps
              inform better decisions.
            </div>
            <div>
              Fully Customizable Improve brand awareness and content
              discoverability through customizable links, supercharging audience
              engagement.
            </div>
          </div>
        </section>

        <section>
          <h2>Boost your links today</h2>
          <button>Get Started</button>
        </section>
        <footer>
          <h3>Shortly</h3>
          <div>Features Link Shortening Branded Links Analytics</div>
          <div>Resources Blog Developers Support</div>
          <div>Company About Our Team Careers Contact</div>
        </footer>
      </div>
    </div>
  );
};

export default Home;

// export const getStaticProps: GetStaticProps = async (context) => {
//   return context
// }
